#include <tk/tkernel.h>
#include <tm/tmonitor.h>

#include "hal_data.h"
#include "usb_loader.h"
#include "video_source.h"
#include "fps_control.h"


#define USB_LOADER_TASK_PRIORITY      (11)
#define USB_LOADER_TASK_STACK_SIZE    (4096)
#define USB_LOADER_PARTITION_NUMBER   (0U)

#define USB_LOADER_SELECT_PATH        "/SELECT.TXT"

#define USB_LOADER_MAX_VIDEO_INDEX    (999U)
#define USB_LOADER_MAX_TARGET_FPS     (120U)

/*
 * Raw USB block-media benchmark.
 *
 * 640 x 480 x 3 bytes = 921600 bytes
 * 921600 / 512 = 1800 sectors
 */
#define USB_BENCHMARK_BLOCK_SIZE_BYTES    (512U)
#define USB_BENCHMARK_BLOCK_SIZE_BYTES (512U)

#define USB_BENCHMARK_BLOCKS_PER_FRAME \
    (VIDEO_SOURCE_FRAME_BYTES / \
     USB_BENCHMARK_BLOCK_SIZE_BYTES)
#define USB_BENCHMARK_FRAME_COUNT         (300U)

/*
 * Read-only test area.
 * No data is written to the USB device.
 */
#define USB_BENCHMARK_START_BLOCK         (2048U)


LOCAL ID s_usb_loader_task_id = 0;

LOCAL FF_Disk_t s_usb_disk;

LOCAL rm_freertos_plus_fat_device_t s_usb_device =
{
    .sector_count      = 0U,
    .sector_size_bytes = 0U,
};

LOCAL uint8_t s_usb_mounted = 0U;

LOCAL void usb_loader_task_entry(INT stacd, void *exinf);

LOCAL fsp_err_t usb_loader_mount(
    usb_event_info_t * event_info);

LOCAL void usb_loader_unmount(void);

LOCAL T_CTSK s_usb_loader_task_ctsk =
{
    .tskatr  = TA_HLNG | TA_RNG3,
    .task    = usb_loader_task_entry,
    .itskpri = USB_LOADER_TASK_PRIORITY,
    .stksz   = USB_LOADER_TASK_STACK_SIZE,
};

LOCAL uint8_t usb_loader_read_config(
    uint32_t * selected_index,
    uint32_t * target_fps
);

LOCAL void usb_loader_make_video_path(
    uint32_t index,
    char path[12]
);

LOCAL size_t usb_loader_read_exact(
    FF_FILE * file,
    uint8_t * destination,
    size_t bytes_to_read
);

LOCAL void usb_loader_run_raw_benchmark(void);

LOCAL void usb_loader_stream_selected_video(void);


ER usb_loader_create(void)
{
    ID task_id;

    task_id = tk_cre_tsk(&s_usb_loader_task_ctsk);

    if (task_id < E_OK)
    {
        return (ER) task_id;
    }

    s_usb_loader_task_id = task_id;

    return E_OK;
}


ER usb_loader_start(void)
{
    if (s_usb_loader_task_id <= 0)
    {
        return E_ID;
    }

    return tk_sta_tsk(s_usb_loader_task_id, 0);
}


LOCAL fsp_err_t usb_loader_mount(
    usb_event_info_t * event_info)
{
    fsp_err_t err;
    FF_Error_t ff_err;

    if ((NULL == event_info) ||
        (NULL == event_info->p_context))
    {
        tm_putstring(
            (UB *)"[USB] mount failed: invalid context.\n"
        );

        return FSP_ERR_INVALID_POINTER;
    }

    /*
     * The HMSC callback context is the block-media USB
     * control structure generated by FSP.
     */
    rm_block_media_usb_instance_ctrl_t * block_media_ctrl =
        (rm_block_media_usb_instance_ctrl_t *)
        event_info->p_context;

    block_media_ctrl->device_address =
        event_info->device_address;

    tm_putstring(
        (UB *)"[USB] MediaInit...\n"
    );

    err = RM_FREERTOS_PLUS_FAT_MediaInit(
        &g_rm_freertos_plus_fat0_ctrl,
        &s_usb_device
    );

    if (FSP_SUCCESS != err)
    {
        tm_printf(
            (UB *)"[USB] MediaInit failed: %d\n",
            err
        );

        return err;
    }

    tm_printf(
        (UB *)"[USB] media: sectors=%u sector_size=%u\n",
        s_usb_device.sector_count,
        s_usb_device.sector_size_bytes
    );


    /*
    * Measure raw USB/HMSC -> SDRAM throughput
    * before FreeRTOS+FAT filesystem processing.
    */
    tm_putstring(
        (UB *)"[USB-Bench] raw block-media test start.\n"
    );

    usb_loader_run_raw_benchmark();

    tm_putstring(
        (UB *)"[USB-Bench] raw block-media test end.\n"
    );


    /*
    * The USB device capacity is determined at runtime.
    */
    g_rm_freertos_plus_fat0_disk_cfg.device.sector_count =
        s_usb_device.sector_count;

    g_rm_freertos_plus_fat0_disk_cfg.device.sector_size_bytes =
        s_usb_device.sector_size_bytes;

    tm_printf(
        (UB *)"[USB] disk cfg: sectors=%u sector_size=%u cache=%u\n",
        g_rm_freertos_plus_fat0_disk_cfg.device.sector_count,
        g_rm_freertos_plus_fat0_disk_cfg.device.sector_size_bytes,
        g_rm_freertos_plus_fat0_disk_cfg.cache_size_bytes
    );

    tm_putstring(
        (UB *)"[USB] DiskInit...\n"
    );

    err = RM_FREERTOS_PLUS_FAT_DiskInit(
        &g_rm_freertos_plus_fat0_ctrl,
        &g_rm_freertos_plus_fat0_disk_cfg,
        &s_usb_disk
    );

    if (FSP_SUCCESS != err)
    {
        tm_printf(
            (UB *)"[USB] DiskInit failed: %d\n",
            err
        );

        return err;
    }

    tm_putstring(
        (UB *)"[USB] FF_Mount...\n"
    );

    ff_err = FF_Mount(
        &s_usb_disk,
        USB_LOADER_PARTITION_NUMBER
    );

    if (FF_ERR_NONE != ff_err)
    {
        tm_printf(
            (UB *)"[USB] FF_Mount failed: %d\n",
            ff_err
        );

        (void) RM_FREERTOS_PLUS_FAT_DiskDeinit(
            &g_rm_freertos_plus_fat0_ctrl,
            &s_usb_disk
        );

        return FSP_ERR_INVALID_DATA;
    }

    int fs_add_result = FF_FS_Add("/", &s_usb_disk);

    if (pdTRUE != fs_add_result)
    {
        tm_putstring(
            (UB *)"[USB] FF_FS_Add failed.\n"
        );

        (void) RM_FREERTOS_PLUS_FAT_DiskDeinit(
            &g_rm_freertos_plus_fat0_ctrl,
            &s_usb_disk
        );

        return FSP_ERR_INTERNAL;
    }

    tm_putstring(
        (UB *)"[USB] filesystem root registered.\n"
    );

    s_usb_mounted = 1U;

    tm_putstring(
        (UB *)"[USB] FAT filesystem mounted.\n"
    );

    return FSP_SUCCESS;
}


LOCAL void usb_loader_unmount(void)
{
    if (0U == s_usb_mounted)
    {
        return;
    }

    fsp_err_t err =
        RM_FREERTOS_PLUS_FAT_DiskDeinit(
            &g_rm_freertos_plus_fat0_ctrl,
            &s_usb_disk
        );

    if (FSP_SUCCESS != err)
    {
        tm_printf(
            (UB *)"[USB] DiskDeinit failed: %d\n",
            err
        );
    }
    else
    {
        tm_putstring(
            (UB *)"[USB] disk deinitialized.\n"
        );
    }

    s_usb_mounted = 0U;
}


LOCAL void usb_loader_task_entry(INT stacd, void *exinf)
{
    fsp_err_t err;

    usb_event_info_t event_info = {0};
    usb_status_t usb_event = USB_STATUS_POWERED;

    uint8_t configured = 0U;
    uint32_t poll_return_count = 0U;

    (void) stacd;
    (void) exinf;

    tm_putstring(
        (UB *)"[USB] task started.\n"
    );

    /*
     * Open the FreeRTOS+FAT port.
     *
     * In this project BSP_CFG_RTOS == 0, so this uses the
     * non-FreeRTOS path while opening the underlying USB
     * block-media/HMSC/basic stack.
     */
    err = RM_FREERTOS_PLUS_FAT_Open(
        &g_rm_freertos_plus_fat0_ctrl,
        &g_rm_freertos_plus_fat0_cfg
    );

    if (FSP_SUCCESS != err)
    {
        tm_printf(
            (UB *)"[USB] open failed: fsp_err=%d\n",
            err
        );

        tk_ext_tsk();
        return;
    }

    tm_putstring(
        (UB *)"[USB] host initialized.\n"
    );

    while (1)
    {
        err = g_basic0.p_api->eventGet(
            &event_info,
            &usb_event
        );

        if (FSP_SUCCESS != err)
        {
            tm_printf(
                (UB *)"[USB] eventGet failed: fsp_err=%d\n",
                err
            );

            tk_dly_tsk(100);
            continue;
        }

        /*
        * If this counter stops after inserting the USB stick,
        * eventGet() itself is not returning.
        */
        poll_return_count++;

        if ((poll_return_count % 100U) == 0U)
        {
            tm_putstring(
                (UB *)"[USB] eventGet alive.\n"
            );
        }

        /*
        * Log every USB event instead of silently ignoring
        * events other than CONFIGURED / DETACH.
        */
        if (USB_STATUS_NONE != usb_event)
        {
            tm_printf(
                (UB *)"[USB] event=%d device_address=%u\n",
                usb_event,
                event_info.device_address
            );
        }

        switch (usb_event)
        {
            case USB_STATUS_CONFIGURED:
            {
                if (0U == configured)
                {
                    tm_printf(
                        (UB *)"[USB] configured: device_address=%u\n",
                        event_info.device_address
                    );

                    err = usb_loader_mount(
                        &event_info
                    );

                    if (FSP_SUCCESS == err)
                    {
                        configured = 1U;
                        usb_loader_stream_selected_video();
                    }
                    else
                    {
                        tm_putstring(
                            (UB *)"[USB] filesystem mount failed.\n"
                        );
                    }
                }

                break;
            }

            case USB_STATUS_DETACH:
            {
                usb_loader_unmount();

                configured = 0U;

                tm_putstring(
                    (UB *)"[USB] detached.\n"
                );

                break;
            }

            default:
            {
                break;
            }
        }

        tk_dly_tsk(10);
    }
}


LOCAL uint8_t usb_loader_read_config(
    uint32_t * selected_index,
    uint32_t * target_fps)
{
    if ((NULL == selected_index) ||
        (NULL == target_fps))
    {
        return 0U;
    }


    FF_FILE * file =
        ff_fopen(
            USB_LOADER_SELECT_PATH,
            "r"
        );

    if (NULL == file)
    {
        tm_putstring(
            (UB *)"[Dataset] SELECT.TXT open failed.\n"
        );

        return 0U;
    }


    uint8_t buffer[32] = {0U};

    size_t read_size =
        ff_fread(
            buffer,
            1U,
            sizeof(buffer) - 1U,
            file
        );

    (void) ff_fclose(file);


    if (0U == read_size)
    {
        tm_putstring(
            (UB *)"[Dataset] SELECT.TXT empty.\n"
        );

        return 0U;
    }


    /*
     * Format:
     *
     * line 1 : video index
     * line 2 : target FPS
     *
     * Example:
     *
     * 10
     * 30
     */
    uint32_t values[2] =
    {
        0U,
        0U
    };

    uint32_t value_index = 0U;
    uint32_t digits = 0U;


    for (size_t i = 0U;
         (i < read_size) &&
         (value_index < 2U);
         i++)
    {
        uint8_t c = buffer[i];


        if ((c >= (uint8_t) '0') &&
            (c <= (uint8_t) '9'))
        {
            values[value_index] =
                (values[value_index] * 10U) +
                (uint32_t)
                (c - (uint8_t) '0');

            digits++;
        }
        else if ((c == (uint8_t) '\r') ||
                 (c == (uint8_t) '\n') ||
                 (c == (uint8_t) ' ')  ||
                 (c == (uint8_t) '\t'))
        {
            if (0U != digits)
            {
                value_index++;
                digits = 0U;
            }
        }
        else
        {
            tm_putstring(
                (UB *)"[Dataset] invalid SELECT.TXT.\n"
            );

            return 0U;
        }
    }


    /*
     * Account for the final number if the file does
     * not end with a newline.
     */
    if ((0U != digits) &&
        (value_index < 2U))
    {
        value_index++;
    }


    if (2U != value_index)
    {
        tm_putstring(
            (UB *)"[Dataset] SELECT.TXT requires "
                   "video index and FPS.\n"
        );

        return 0U;
    }


    if (values[0] >
        USB_LOADER_MAX_VIDEO_INDEX)
    {
        tm_putstring(
            (UB *)"[Dataset] selected index too large.\n"
        );

        return 0U;
    }


    if (values[1] >
        USB_LOADER_MAX_TARGET_FPS)
    {
        tm_putstring(
            (UB *)"[FPS] target FPS too large.\n"
        );

        return 0U;
    }


    *selected_index =
        values[0];

    *target_fps =
        values[1];


    return 1U;
}


LOCAL void usb_loader_make_video_path(
    uint32_t index,
    char path[12])
{
    /*
     * "/VID000.R56"
     *
     * 11 characters + '\0'
     */
    path[0]  = '/';
    path[1]  = 'V';
    path[2]  = 'I';
    path[3]  = 'D';

    path[4] =
        (char) ('0' + ((index / 100U) % 10U));

    path[5] =
        (char) ('0' + ((index / 10U) % 10U));

    path[6] =
        (char) ('0' + (index % 10U));

    path[7]  = '.';
    path[8]  = 'R';
    path[9]  = '5';
    path[10] = '6';
    path[11] = '\0';
}


LOCAL size_t usb_loader_read_exact(
    FF_FILE * file,
    uint8_t * destination,
    size_t bytes_to_read)
{
    if ((NULL == file) ||
        (NULL == destination))
    {
        return 0U;
    }


    size_t total_read = 0U;

    while (total_read < bytes_to_read)
    {
        size_t read_size =
            ff_fread(
                destination + total_read,
                1U,
                bytes_to_read - total_read,
                file
            );

        if (0U == read_size)
        {
            break;
        }

        total_read += read_size;
    }


    return total_read;
}


LOCAL void usb_loader_run_raw_benchmark(void)
{
    uint32_t slot = 0U;

    uint8_t * buffer =
        video_source_acquire_write_buffer(
            &slot
        );

    if (NULL == buffer)
    {
        tm_putstring(
            (UB *)"[USB-Bench] no SDRAM buffer available.\n"
        );

        return;
    }


    SYSTIM start_time;
    SYSTIM end_time;

    ER time_err =
        tk_get_otm(
            &start_time
        );

    if (time_err < E_OK)
    {
        video_source_cancel_write_buffer(
            slot
        );

        tm_putstring(
            (UB *)"[USB-Bench] tk_get_otm start failed.\n"
        );

        return;
    }


    uint32_t completed = 0U;

    for (uint32_t i = 0U;
         i < USB_BENCHMARK_FRAME_COUNT;
         i++)
    {
        uint32_t block_address =
            USB_BENCHMARK_START_BLOCK +
            (i * USB_BENCHMARK_BLOCKS_PER_FRAME);

        fsp_err_t err =
            g_rm_block_media0.p_api->read(
                g_rm_block_media0.p_ctrl,
                buffer,
                block_address,
                USB_BENCHMARK_BLOCKS_PER_FRAME
            );

        if (FSP_SUCCESS != err)
        {
            tm_printf(
                (UB *)"[USB-Bench] read failed: "
                       "index=%u block=%u err=%d\n",
                i,
                block_address,
                err
            );

            break;
        }

        completed++;
    }


    time_err =
        tk_get_otm(
            &end_time
        );


    video_source_cancel_write_buffer(
        slot
    );


    if (time_err < E_OK)
    {
        tm_putstring(
            (UB *)"[USB-Bench] tk_get_otm end failed.\n"
        );

        return;
    }


    uint64_t start_ms =
        ((uint64_t) (uint32_t) start_time.hi << 32) |
        start_time.lo;

    uint64_t end_ms =
        ((uint64_t) (uint32_t) end_time.hi << 32) |
        end_time.lo;

    uint64_t elapsed_ms =
        end_ms - start_ms;


    if ((0U == completed) ||
        (0U == elapsed_ms))
    {
        return;
    }


    uint64_t total_bytes =
        (uint64_t) completed *
        USB_BENCHMARK_BLOCKS_PER_FRAME *
        USB_BENCHMARK_BLOCK_SIZE_BYTES;


    /*
     * MB/s x 1000.
     */
    uint32_t mbps_x1000 =
        (uint32_t)
        (
            (total_bytes * 1000ULL) /
            elapsed_ms /
            1000ULL
        );


    tm_printf(
        (UB *)"[USB-Bench] "
               "frames=%u "
               "bytes=%u "
               "elapsed_ms=%u "
               "MBps=%u.%03u\n",
        completed,
        (uint32_t) total_bytes,
        (uint32_t) elapsed_ms,
        mbps_x1000 / 1000U,
        mbps_x1000 % 1000U
    );
}


LOCAL void usb_loader_stream_selected_video(void)
{
    uint32_t selected_index = 0U;
    uint32_t target_fps = 0U;


    if (0U ==
        usb_loader_read_config(
            &selected_index,
            &target_fps))
    {
        return;
    }


    /*
     * Apply the requested FPS before streaming
     * starts.
     *
     * 0 means unlimited.
     */
    fps_control_set_target_fps(
        target_fps
    );


    tm_printf(
        (UB *)"[FPS] configured from SELECT.TXT: %u\n",
        target_fps
    );


    char path[12];

    usb_loader_make_video_path(
        selected_index,
        path
    );


    tm_printf(
        (UB *)"[Dataset] selected=%u file=%s\n",
        selected_index,
        path
    );


    FF_FILE * file =
        ff_fopen(
            path,
            "rb"
        );

    if (NULL == file)
    {
        tm_printf(
            (UB *)"[Dataset] file not found: %s\n",
            path
        );

        return;
    }


    /*
     * File size is used only to determine whether the RAW file
     * consists of complete frames.
     *
     * The complete file is NOT read here.
     */
    size_t file_size =
        ff_filelength(file);

    tm_printf(
        (UB *)"[Dataset] file_size=%u bytes\n",
        (uint32_t) file_size
    );


    if (0U == file_size)
    {
        tm_putstring(
            (UB *)"[Dataset] empty RAW file.\n"
        );

        (void) ff_fclose(file);

        return;
    }


    /*
     * RAW must contain an integer number of complete
     * 640 x 480 x 3-byte frames.
     */
    if ((file_size %
         VIDEO_SOURCE_FRAME_BYTES) != 0U)
    {
        tm_printf(
            (UB *)"[Dataset] invalid RAW size: "
                   "bytes=%u frame_bytes=%u remainder=%u\n",
            (uint32_t) file_size,
            VIDEO_SOURCE_FRAME_BYTES,
            (uint32_t)
            (file_size %
             VIDEO_SOURCE_FRAME_BYTES)
        );

        (void) ff_fclose(file);

        return;
    }


    uint32_t frame_count =
        (uint32_t)
        (file_size /
         VIDEO_SOURCE_FRAME_BYTES);


    tm_printf(
        (UB *)"[Dataset] streaming start: "
               "frames=%u frame_bytes=%u\n",
        frame_count,
        VIDEO_SOURCE_FRAME_BYTES
    );


    uint32_t frames_published = 0U;


    for (uint32_t frame_index = 0U;
         frame_index < frame_count;
         frame_index++)
    {
        uint32_t slot = 0U;
        uint8_t * frame_buffer = NULL;


        /*
         * Wait until the next SDRAM input buffer becomes EMPTY.
         *
         * This provides back-pressure:
         * USB cannot overwrite a frame still being used
         * by the display task.
         */
        while (NULL == frame_buffer)
        {
            frame_buffer =
                video_source_acquire_write_buffer(
                    &slot
                );

            if (NULL == frame_buffer)
            {
                tk_dly_tsk(1);
            }
        }


        /*
         * Read exactly one video frame directly from FAT
         * into the SDRAM input buffer.
         *
         * No 4 KiB staging buffer and no whole-file CRC.
         */
        fps_control_usb_read_begin(
            frame_index
        );

        size_t read_size =
            usb_loader_read_exact(
                file,
                frame_buffer,
                VIDEO_SOURCE_FRAME_BYTES
            );

        fps_control_usb_read_end();


        if (VIDEO_SOURCE_FRAME_BYTES !=
            read_size)
        {
            int fat_errno =
                stdioGET_ERRNO();


            /*
             * This buffer never became a complete frame,
             * so return it from WRITING to EMPTY.
             */
            video_source_cancel_write_buffer(
                slot
            );


            tm_printf(
                (UB *)"[Dataset] frame read failed: "
                       "frame=%u expected=%u actual=%u errno=%d\n",
                frame_index,
                VIDEO_SOURCE_FRAME_BYTES,
                (uint32_t) read_size,
                fat_errno
            );

            break;
        }


        /*
         * The frame is complete.
         *
         * Transfer ownership from USB producer to
         * the display consumer.
         */
        video_source_publish_write_buffer(
            slot,
            frame_index
        );


        frames_published++;
    }


    int close_result =
        ff_fclose(file);

    if (0 != close_result)
    {
        tm_printf(
            (UB *)"[Dataset] close failed: %d\n",
            close_result
        );
    }


    tm_printf(
        (UB *)"[Dataset] streaming end: "
               "published=%u/%u frames\n",
        frames_published,
        frame_count
    );
}
