#include <tk/tkernel.h>
#include <tm/tmonitor.h>

#include "hal_data.h"
#include "usb_loader.h"
#include "video_cache.h"


#define USB_LOADER_TASK_PRIORITY      (32)
#define USB_LOADER_TASK_STACK_SIZE    (4096)
#define USB_LOADER_PARTITION_NUMBER   (0U)

#define USB_LOADER_SELECT_PATH              "/SELECT.TXT"

#define USB_LOADER_FRAME_WIDTH              (640U)
#define USB_LOADER_FRAME_HEIGHT             (480U)
#define USB_LOADER_FRAME_CHANNELS           (3U)

#define USB_LOADER_FRAME_BYTES              \
    (USB_LOADER_FRAME_WIDTH *               \
     USB_LOADER_FRAME_HEIGHT *              \
     USB_LOADER_FRAME_CHANNELS)

#define USB_LOADER_VIDEO_FPS                (10U)

#define USB_LOADER_DATASET_READ_CHUNK_BYTES (4096U)

#define USB_LOADER_MAX_VIDEO_INDEX          (999U)


LOCAL ID s_usb_loader_task_id = 0;

LOCAL FF_Disk_t s_usb_disk;

LOCAL rm_freertos_plus_fat_device_t s_usb_device =
{
    .sector_count      = 0U,
    .sector_size_bytes = 0U,
};

LOCAL uint8_t s_usb_mounted = 0U;

LOCAL uint8_t s_dataset_read_buffer[USB_LOADER_DATASET_READ_CHUNK_BYTES];

LOCAL void usb_loader_task_entry(INT stacd, void *exinf);

LOCAL fsp_err_t usb_loader_mount(
    usb_event_info_t * event_info);

LOCAL void usb_loader_unmount(void);

LOCAL T_CTSK s_usb_loader_task_ctsk =
{
    .tskatr  = TA_HLNG | TA_RNG3,
    .task    = usb_loader_task_entry,
    .itskpri = USB_LOADER_TASK_PRIORITY,
    .stksz   = USB_LOADER_TASK_STACK_SIZE,
};

LOCAL uint8_t usb_loader_read_selection(
    uint32_t * selected_index
);

LOCAL void usb_loader_make_video_path(
    uint32_t index,
    char path[12]
);

LOCAL void usb_loader_test_selected_video(void);


ER usb_loader_create(void)
{
    ID task_id;

    task_id = tk_cre_tsk(&s_usb_loader_task_ctsk);

    if (task_id < E_OK)
    {
        return (ER) task_id;
    }

    s_usb_loader_task_id = task_id;

    return E_OK;
}


ER usb_loader_start(void)
{
    if (s_usb_loader_task_id <= 0)
    {
        return E_ID;
    }

    return tk_sta_tsk(s_usb_loader_task_id, 0);
}


LOCAL fsp_err_t usb_loader_mount(
    usb_event_info_t * event_info)
{
    fsp_err_t err;
    FF_Error_t ff_err;

    if ((NULL == event_info) ||
        (NULL == event_info->p_context))
    {
        tm_putstring(
            (UB *)"[USB] mount failed: invalid context.\n"
        );

        return FSP_ERR_INVALID_POINTER;
    }

    /*
     * The HMSC callback context is the block-media USB
     * control structure generated by FSP.
     */
    rm_block_media_usb_instance_ctrl_t * block_media_ctrl =
        (rm_block_media_usb_instance_ctrl_t *)
        event_info->p_context;

    block_media_ctrl->device_address =
        event_info->device_address;

    tm_putstring(
        (UB *)"[USB] MediaInit...\n"
    );

    err = RM_FREERTOS_PLUS_FAT_MediaInit(
        &g_rm_freertos_plus_fat0_ctrl,
        &s_usb_device
    );

    if (FSP_SUCCESS != err)
    {
        tm_printf(
            (UB *)"[USB] MediaInit failed: %d\n",
            err
        );

        return err;
    }

    tm_printf(
        (UB *)"[USB] media: sectors=%u sector_size=%u\n",
        s_usb_device.sector_count,
        s_usb_device.sector_size_bytes
    );

    /*
    * The USB device capacity is determined at runtime.
    * Update the generated FAT disk configuration with the
    * actual media information before creating the disk.
    */
    g_rm_freertos_plus_fat0_disk_cfg.device.sector_count =
        s_usb_device.sector_count;

    g_rm_freertos_plus_fat0_disk_cfg.device.sector_size_bytes =
        s_usb_device.sector_size_bytes;

    tm_printf(
        (UB *)"[USB] disk cfg: sectors=%u sector_size=%u cache=%u\n",
        g_rm_freertos_plus_fat0_disk_cfg.device.sector_count,
        g_rm_freertos_plus_fat0_disk_cfg.device.sector_size_bytes,
        g_rm_freertos_plus_fat0_disk_cfg.cache_size_bytes
    );

    tm_putstring(
        (UB *)"[USB] DiskInit...\n"
    );

    err = RM_FREERTOS_PLUS_FAT_DiskInit(
        &g_rm_freertos_plus_fat0_ctrl,
        &g_rm_freertos_plus_fat0_disk_cfg,
        &s_usb_disk
    );

    if (FSP_SUCCESS != err)
    {
        tm_printf(
            (UB *)"[USB] DiskInit failed: %d\n",
            err
        );

        return err;
    }

    tm_putstring(
        (UB *)"[USB] FF_Mount...\n"
    );

    ff_err = FF_Mount(
        &s_usb_disk,
        USB_LOADER_PARTITION_NUMBER
    );

    if (FF_ERR_NONE != ff_err)
    {
        tm_printf(
            (UB *)"[USB] FF_Mount failed: %d\n",
            ff_err
        );

        (void) RM_FREERTOS_PLUS_FAT_DiskDeinit(
            &g_rm_freertos_plus_fat0_ctrl,
            &s_usb_disk
        );

        return FSP_ERR_INVALID_DATA;
    }

    int fs_add_result = FF_FS_Add("/", &s_usb_disk);

    if (pdTRUE != fs_add_result)
    {
        tm_putstring(
            (UB *)"[USB] FF_FS_Add failed.\n"
        );

        (void) RM_FREERTOS_PLUS_FAT_DiskDeinit(
            &g_rm_freertos_plus_fat0_ctrl,
            &s_usb_disk
        );

        return FSP_ERR_INTERNAL;
    }

    tm_putstring(
        (UB *)"[USB] filesystem root registered.\n"
    );

    s_usb_mounted = 1U;

    tm_putstring(
        (UB *)"[USB] FAT filesystem mounted.\n"
    );

    return FSP_SUCCESS;
}


LOCAL void usb_loader_unmount(void)
{
    if (0U == s_usb_mounted)
    {
        return;
    }

    fsp_err_t err =
        RM_FREERTOS_PLUS_FAT_DiskDeinit(
            &g_rm_freertos_plus_fat0_ctrl,
            &s_usb_disk
        );

    if (FSP_SUCCESS != err)
    {
        tm_printf(
            (UB *)"[USB] DiskDeinit failed: %d\n",
            err
        );
    }
    else
    {
        tm_putstring(
            (UB *)"[USB] disk deinitialized.\n"
        );
    }

    s_usb_mounted = 0U;
}


LOCAL void usb_loader_task_entry(INT stacd, void *exinf)
{
    fsp_err_t err;

    usb_event_info_t event_info = {0};
    usb_status_t usb_event = USB_STATUS_POWERED;

    uint8_t configured = 0U;
    uint32_t poll_return_count = 0U;

    (void) stacd;
    (void) exinf;

    tm_putstring(
        (UB *)"[USB] task started.\n"
    );

    /*
     * Open the FreeRTOS+FAT port.
     *
     * In this project BSP_CFG_RTOS == 0, so this uses the
     * non-FreeRTOS path while opening the underlying USB
     * block-media/HMSC/basic stack.
     */
    err = RM_FREERTOS_PLUS_FAT_Open(
        &g_rm_freertos_plus_fat0_ctrl,
        &g_rm_freertos_plus_fat0_cfg
    );

    if (FSP_SUCCESS != err)
    {
        tm_printf(
            (UB *)"[USB] open failed: fsp_err=%d\n",
            err
        );

        tk_ext_tsk();
        return;
    }

    tm_putstring(
        (UB *)"[USB] host initialized.\n"
    );

    while (1)
    {
        err = g_basic0.p_api->eventGet(
            &event_info,
            &usb_event
        );

        if (FSP_SUCCESS != err)
        {
            tm_printf(
                (UB *)"[USB] eventGet failed: fsp_err=%d\n",
                err
            );

            tk_dly_tsk(100);
            continue;
        }

        /*
        * If this counter stops after inserting the USB stick,
        * eventGet() itself is not returning.
        */
        poll_return_count++;

        if ((poll_return_count % 100U) == 0U)
        {
            tm_putstring(
                (UB *)"[USB] eventGet alive.\n"
            );
        }

        /*
        * Log every USB event instead of silently ignoring
        * events other than CONFIGURED / DETACH.
        */
        if (USB_STATUS_NONE != usb_event)
        {
            tm_printf(
                (UB *)"[USB] event=%d device_address=%u\n",
                usb_event,
                event_info.device_address
            );
        }

        switch (usb_event)
        {
            case USB_STATUS_CONFIGURED:
            {
                if (0U == configured)
                {
                    tm_printf(
                        (UB *)"[USB] configured: device_address=%u\n",
                        event_info.device_address
                    );

                    err = usb_loader_mount(
                        &event_info
                    );

                    if (FSP_SUCCESS == err)
                    {
                        configured = 1U;
                        usb_loader_test_selected_video();
                    }
                    else
                    {
                        tm_putstring(
                            (UB *)"[USB] filesystem mount failed.\n"
                        );
                    }
                }

                break;
            }

            case USB_STATUS_DETACH:
            {
                usb_loader_unmount();

                configured = 0U;

                tm_putstring(
                    (UB *)"[USB] detached.\n"
                );

                break;
            }

            default:
            {
                break;
            }
        }

        tk_dly_tsk(10);
    }
}


LOCAL uint8_t usb_loader_read_selection(
    uint32_t * selected_index)
{
    if (NULL == selected_index)
    {
        return 0U;
    }

    FF_FILE * file =
        ff_fopen(
            USB_LOADER_SELECT_PATH,
            "r"
        );

    if (NULL == file)
    {
        tm_putstring(
            (UB *)"[Dataset] SELECT.TXT open failed.\n"
        );

        return 0U;
    }

    uint8_t buffer[8] = {0U};

    size_t read_size =
        ff_fread(
            buffer,
            1U,
            sizeof(buffer),
            file
        );

    (void) ff_fclose(file);

    if (0U == read_size)
    {
        tm_putstring(
            (UB *)"[Dataset] SELECT.TXT empty.\n"
        );

        return 0U;
    }


    uint32_t value = 0U;
    uint32_t digits = 0U;

    for (size_t i = 0U; i < read_size; i++)
    {
        uint8_t c = buffer[i];

        if ((c == (uint8_t) '\r') ||
            (c == (uint8_t) '\n') ||
            (c == (uint8_t) ' '))
        {
            break;
        }

        if ((c < (uint8_t) '0') ||
            (c > (uint8_t) '9'))
        {
            tm_putstring(
                (UB *)"[Dataset] invalid SELECT.TXT.\n"
            );

            return 0U;
        }

        value =
            (value * 10U) +
            (uint32_t) (c - (uint8_t) '0');

        digits++;

        if (value > USB_LOADER_MAX_VIDEO_INDEX)
        {
            tm_putstring(
                (UB *)"[Dataset] selected index too large.\n"
            );

            return 0U;
        }
    }

    if (0U == digits)
    {
        return 0U;
    }

    *selected_index = value;

    return 1U;
}


LOCAL void usb_loader_make_video_path(
    uint32_t index,
    char path[12])
{
    /*
     * "/VID000.RAW"
     *
     * 11 characters + '\0'
     */
    path[0]  = '/';
    path[1]  = 'V';
    path[2]  = 'I';
    path[3]  = 'D';

    path[4] =
        (char) ('0' + ((index / 100U) % 10U));

    path[5] =
        (char) ('0' + ((index / 10U) % 10U));

    path[6] =
        (char) ('0' + (index % 10U));

    path[7]  = '.';
    path[8]  = 'R';
    path[9]  = 'A';
    path[10] = 'W';
    path[11] = '\0';
}


LOCAL void usb_loader_test_selected_video(void)
{
    uint32_t selected_index = 0U;

    if (0U ==
        usb_loader_read_selection(
            &selected_index))
    {
        return;
    }


    char path[12];

    usb_loader_make_video_path(
        selected_index,
        path
    );


    tm_printf(
        (UB *)"[Dataset] selected=%u file=%s\n",
        selected_index,
        path
    );


    FF_FILE * file =
        ff_fopen(
            path,
            "rb"
        );

    if (NULL == file)
    {
        tm_printf(
            (UB *)"[Dataset] file not found: %s\n",
            path
        );

        return;
    }


    size_t file_size = ff_filelength(file);

    tm_printf(
        (UB *)"[Dataset] file_size=%u bytes\n",
        (uint32_t) file_size
    );


    uint32_t total_bytes = 0U;

    uint32_t crc =
        0xFFFFFFFFUL;

    uint32_t next_report =
        32UL * 1024UL * 1024UL;


    while (1)
    {
        size_t read_size =
            ff_fread(
                s_dataset_read_buffer,
                1U,
                USB_LOADER_DATASET_READ_CHUNK_BYTES,
                file
            );

        if (0U == read_size)
        {
            int fat_errno = stdioGET_ERRNO();

            if (0U == total_bytes)
            {
                tm_printf(
                    (UB *)"[Dataset] first ff_fread returned 0 bytes, errno=%d\n",
                    fat_errno
                );
            }

            break;
        }

        crc =
            video_cache_crc32_update(
                crc,
                s_dataset_read_buffer,
                (uint32_t) read_size
            );


        total_bytes +=
            (uint32_t) read_size;


        if (total_bytes >= next_report)
        {
            tm_printf(
                (UB *)"[Dataset] progress=%u MiB\n",
                total_bytes /
                (1024UL * 1024UL)
            );

            next_report +=
                32UL * 1024UL * 1024UL;
        }
    }


    int close_result =
        ff_fclose(file);

    if (0 != close_result)
    {
        tm_printf(
            (UB *)"[Dataset] close failed: %d\n",
            close_result
        );

        return;
    }


    if (0U == total_bytes)
    {
        tm_putstring(
            (UB *)"[Dataset] no payload bytes were read.\n"
        );

        return;
    }


    crc ^=
        0xFFFFFFFFUL;


    /*
     * RAW must contain an integer number of complete frames.
     */
    if ((total_bytes % USB_LOADER_FRAME_BYTES) != 0U)
    {
        tm_printf(
            (UB *)"[Dataset] invalid RAW size: "
            "bytes=%u frame_bytes=%u remainder=%u\n",
            total_bytes,
            USB_LOADER_FRAME_BYTES,
            total_bytes % USB_LOADER_FRAME_BYTES
        );

        return;
    }


    uint32_t frame_count =
        total_bytes /
        USB_LOADER_FRAME_BYTES;

    uint32_t duration_ms =
        (frame_count * 1000U) /
        USB_LOADER_VIDEO_FPS;


    tm_printf(
        (UB *)"[Dataset] complete: "
        "index=%u bytes=%u frames=%u "
        "duration_ms=%u crc=0x%08X\n",
        selected_index,
        total_bytes,
        frame_count,
        duration_ms,
        crc
    );

    tm_putstring(
        (UB *)"[Dataset] RAW validation OK.\n"
    );
}
